<?php

/**
 * Implements hook_menu().
 */
function uikit_examples_menu() {
  $items['layouts'] = array(
    'title' => t('Layout examples'),
    'page callback' => 'uikit_layouts',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.module',
    'file path' => drupal_get_path('module', 'uikit_examples'),
    'module' => 'uikit_examples',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -49,
    'expanded' => TRUE,
    'options' => array(
      'attributes' => array(
        'docs-nolink' => '',
      ),
    ),
  );
  $items['layouts/7.x-2.x'] = array(
    'title' => t('7.x-2.x'),
    'page callback' => 'uikit_layouts_7x_2x',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.module',
    'file path' => drupal_get_path('module', 'uikit_examples'),
    'module' => 'uikit_examples',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -50,
    'expanded' => TRUE,
    'options' => array(
      'attributes' => array(
        'docs-nolink' => '',
        'docs-nav-divider' => '',
        'class' => array('uk-nav-header'),
      ),
    ),
  );
  $items['layouts/7.x-3.x'] = array(
    'title' => t('7.x-3.x'),
    'page callback' => 'uikit_layouts_7x_3x',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.module',
    'file path' => drupal_get_path('module', 'uikit_examples'),
    'module' => 'uikit_examples',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -49,
    'expanded' => TRUE,
    'options' => array(
      'attributes' => array(
        'docs-nolink' => '',
        'docs-nav-divider' => '',
        'class' => array('uk-nav-header'),
      ),
    ),
  );
  $items['layouts/8.x-2.x'] = array(
    'title' => t('8.x-2.x'),
    'page callback' => 'uikit_layouts_8x_2x',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.module',
    'file path' => drupal_get_path('module', 'uikit_examples'),
    'module' => 'uikit_examples',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -48,
    'expanded' => TRUE,
    'options' => array(
      'attributes' => array(
        'docs-nolink' => '',
        'docs-nav-divider' => '',
        'class' => array('uk-nav-header'),
      ),
    ),
  );
  $items['layouts/8.x-3.x'] = array(
    'title' => t('8.x-3.x'),
    'page callback' => 'uikit_layouts_8x_3x',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.module',
    'file path' => drupal_get_path('module', 'uikit_examples'),
    'module' => 'uikit_examples',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -47,
    'expanded' => TRUE,
    'options' => array(
      'attributes' => array(
        'docs-nolink' => '',
        'docs-nav-divider' => '',
        'class' => array('uk-nav-header'),
      ),
    ),
  );
  $items['layouts/7.x-2.x/frontpage'] = array(
    'title' => t('Frontpage'),
    'page callback' => 'uikit_layouts_7x_2x_frontpage',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.module',
    'file path' => drupal_get_path('module', 'uikit_examples'),
    'module' => 'uikit_examples',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -50,
  );
  $items['layouts/7.x-2.x/portfolio'] = array(
    'title' => t('Portfolio'),
    'page callback' => 'uikit_layouts_7x_2x_portfolio',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.module',
    'file path' => drupal_get_path('module', 'uikit_examples'),
    'module' => 'uikit_examples',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -49,
  );
  $items['layouts/7.x-2.x/blog'] = array(
    'title' => t('Blog'),
    'page callback' => 'uikit_layouts_7x_2x_blog',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.module',
    'file path' => drupal_get_path('module', 'uikit_examples'),
    'module' => 'uikit_examples',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -48,
  );
  $items['layouts/7.x-2.x/post'] = array(
    'title' => t('Blog post'),
    'page callback' => 'uikit_layouts_7x_2x_post',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.module',
    'file path' => drupal_get_path('module', 'uikit_examples'),
    'module' => 'uikit_examples',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -47,
  );
  $items['layouts/7.x-2.x/documentation'] = array(
    'title' => t('Documentation'),
    'page callback' => 'uikit_layouts_7x_2x_documentation',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.module',
    'file path' => drupal_get_path('module', 'uikit_examples'),
    'module' => 'uikit_examples',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -46,
  );
  $items['layouts/7.x-2.x/contact'] = array(
    'title' => t('Contact'),
    'page callback' => 'uikit_layouts_7x_2x_contact',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.module',
    'file path' => drupal_get_path('module', 'uikit_examples'),
    'module' => 'uikit_examples',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -45,
  );
  $items['layouts/7.x-3.x/coming-soon'] = array(
    'title' => t('Coming soon!'),
    'page callback' => 'uikit_layouts_7x_3x_frontpage',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.module',
    'file path' => drupal_get_path('module', 'uikit_examples'),
    'module' => 'uikit_examples',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -50,
    'options' => array(
      'attributes' => array(
        'docs-nolink' => '',
        'docs-reset-link' => '',
      ),
    ),
  );
  $items['layouts/8.x-2.x/coming-soon'] = array(
    'title' => t('Coming soon!'),
    'page callback' => 'uikit_layouts_8x_2x_frontpage',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.module',
    'file path' => drupal_get_path('module', 'uikit_examples'),
    'module' => 'uikit_examples',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -50,
    'options' => array(
      'attributes' => array(
        'docs-nolink' => '',
        'docs-reset-link' => '',
      ),
    ),
  );
  $items['layouts/8.x-3.x/coming-soon'] = array(
    'title' => t('Coming soon!'),
    'page callback' => 'uikit_layouts_8x_3x_frontpage',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.module',
    'file path' => drupal_get_path('module', 'uikit_examples'),
    'module' => 'uikit_examples',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -50,
    'options' => array(
      'attributes' => array(
        'docs-nolink' => '',
        'docs-reset-link' => '',
      ),
    ),
  );

  return $items;
}

/**
 * Page callback for the screenshots page.
 */
function uikit_layouts_7x_2x_frontpage() {
  $module = drupal_get_path('module', 'uikit_examples');
  $filename = $module . '/includes/2.x/layouts_frontpage.inc';
  $handle = fopen($filename, "r");
  $contents = fread($handle, filesize($filename));
  fclose($handle);

  $output = check_markup($contents, $format_id = 'demo_html');
  return $output;
}

/**
 * Page callback for the screenshots page.
 */
function uikit_layouts_7x_2x_portfolio() {
  $module = drupal_get_path('module', 'uikit_examples');
  $filename = $module . '/includes/2.x/layouts_portfolio.inc';
  $handle = fopen($filename, "r");
  $contents = fread($handle, filesize($filename));
  fclose($handle);

  $output = check_markup($contents, $format_id = 'demo_html');
  return $output;
}

/**
 * Page callback for the screenshots page.
 */
function uikit_layouts_7x_2x_blog() {
  $module = drupal_get_path('module', 'uikit_examples');
  $filename = $module . '/includes/2.x/layouts_blog.inc';
  $handle = fopen($filename, "r");
  $contents = fread($handle, filesize($filename));
  fclose($handle);

  $output = check_markup($contents, $format_id = 'demo_html');
  return $output;
}

/**
 * Page callback for the screenshots page.
 */
function uikit_layouts_7x_2x_post() {
  $module = drupal_get_path('module', 'uikit_examples');
  $filename = $module . '/includes/2.x/layouts_post.inc';
  $handle = fopen($filename, "r");
  $contents = fread($handle, filesize($filename));
  fclose($handle);

  $output = check_markup($contents, $format_id = 'demo_html');
  return $output;
}

/**
 * Page callback for the screenshots page.
 */
function uikit_layouts_7x_2x_documentation() {
  uikit_get_cdn_asset('sticky');
  $module = drupal_get_path('module', 'uikit_examples');
  $filename = $module . '/includes/2.x/layouts_documentation.inc';
  $handle = fopen($filename, "r");
  $contents = fread($handle, filesize($filename));
  fclose($handle);

  $output = check_markup($contents, $format_id = 'demo_html');
  return $output;
}

/**
 * Page callback for the screenshots page.
 */
function uikit_layouts_7x_2x_contact() {
  $module = drupal_get_path('module', 'uikit_examples');
  $filename = $module . '/includes/2.x/layouts_contact.inc';
  $handle = fopen($filename, "r");
  $contents = fread($handle, filesize($filename));
  fclose($handle);

  $output = check_markup($contents, $format_id = 'demo_html');
  return $output;
}
