<?php

/**
 * @file
 * Conditional logic and data processing for STARTERKIT.
 */

/**
 * Load STARTERKIT's include files for theme processing.
 */
uikit_load_include('inc', 'STARTERKIT', 'preprocess', 'includes');
uikit_load_include('inc', 'STARTERKIT', 'process', 'includes');
uikit_load_include('inc', 'STARTERKIT', 'theme', 'includes');
uikit_load_include('inc', 'STARTERKIT', 'alter', 'includes');
