<?php

/**
 * @file
 * Helper module for the docs theme.
 */

/**
 * Implements hook_block_info().
 */
function docs_companion_block_info() {
  $blocks = array();

  $blocks['docs-companion-copyright'] = array(
    'info' => t('Docs copyright'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function docs_companion_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'docs-companion-copyright':
      $block['subject'] = '';
      $block['content'] = _docs_companion_copyright_block();
      break;
  }

  return $block;
}

/**
 * Implements hook_menu_alter().
 */
function docs_companion_menu_alter(&$items) {
  $items['node']['page callback'] = '_docs_redirect_node_page';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function docs_companion_preprocess_menu_link(&$variables) {
  $href = $variables['element']['#href'];

  if ($href == 'user/login' || $href == 'user/logout') {
    $current_path = drupal_get_path_alias();
    $variables['element']['#localized_options']['query']['destination'] = $current_path;
  }
}

/**
 * Constructs the content for the copyright block.
 *
 * @return null|string
 *   Returns the content for the copyright block.
 */
function _docs_companion_copyright_block() {
  $module = drupal_get_path('module', 'docs_companion');
  $filename = $module . '/inc/copyright.inc';
  $handle = fopen($filename, "r");
  $contents = fread($handle, filesize($filename));
  fclose($handle);

  $output = check_markup($contents, $format_id = 'full_html');
  return $output;
}

function _docs_redirect_node_page() {
  drupal_goto('<front>');
}
