<?php

/**
 * @file
 * The UIkit theme system, which controls the output of the UIkit theme.
 *
 * The theme system allows for nearly all output of the Drupal system to be
 * customized by UIkit themes.
 *
 * @ingroup uikit_themeable
 */

/**
 * Implements hook_theme().
 */
/* -- Delete this line if you want to use this function
function STARTERKIT_theme($existing, $type, $theme, $path) {
}
// */
