<ul class="uk-subnav uk-subnav-line uk-flex-center">
  <li><a href="https://www.drupal.org/project/uikit" target="_blank">Drupal Project Page</a></li>
  <li><a href="https://www.drupal.org/project/issues/uikit?categories=All" target="_blank">Issues</a></li>
  <li><a href="https://www.drupal.org/list-changes/uikit" target="_blank">Changelog</a></li>
</ul>
<p><i class="uk-icon-copyright"></i> <a href="http://www.yootheme.com" target="_blank">YOOtheme</a>, with love and caffeine, under the <a href="http://opensource.org/licenses/MIT" target="_blank">MIT license</a>.<br>Ported to Drupal by <a href="http://richardbuchanan.com" target="_blank">Richard Buchanan</a>.</p>
