<div class="docs-section docs-section-color-1 docs-section-colored">
  <div class="uk-container uk-container-center uk-text-center">

    <img class="docs-logo" src="/profiles/uikit_api/images/uikit-contrast-small.png" width="300" height="239" alt="UIkit">

    <p class="uk-text-large uk-margin-large-top">A lightweight and modular front-end framework<br class="uk-hidden-small"> for developing fast and powerful web interfaces with Drupal.</p>

    <a class="uk-button uk-button-large docs-button-download uk-margin-right" href="https://www.drupal.org/project/uikit/releases/UIKIT_7X_2X_CURRENT_VERSION">Download UIkit UIKIT_7X_2X_CURRENT_VERSION</a><a class="uk-button uk-button-large docs-button-download" href="https://www.drupal.org/project/uikit/releases/UIKIT_8X_2X_CURRENT_VERSION">Download UIkit UIKIT_8X_2X_CURRENT_VERSION</a>

    <ul class="docs-subnav uk-subnav uk-subnav-line uk-flex-center">
      <li><a href="https://www.drupal.org/project/uikit">UIkit on Drupal</a><sup class="docs-sup">[1]</sup></li>
      <li><a href="/api/uikit">Developer API</a></li>
      <li>Latest Versions: UIKIT_7X_2X_CURRENT_VERSION/UIKIT_8X_2X_CURRENT_VERSION</li>
    </ul>
    <ul class="docs-subnav docs-subnav-blockquote uk-subnav uk-flex-center uk-margin-large-top">
      <li>
        <blockquote class="docs-blockquote">
          <h2><i class="uk-icon-quote-left uk-icon-large uk-align-left"></i><span class="docs-blockquote-top">Come for the code, stay for the community</span></h2>
        </blockquote>
      </li>
    </ul>

  </div>
</div>

<div class="docs-section docs-section-color-white">
  <div class="uk-container uk-container-center uk-text-center">

    <h1 class="docs-margin-large-bottom"><strong>Get involved.</strong> Become a part of the UIkit community.</h1>

    <div class="uk-grid docs-grid-margin-large" data-uk-grid-match="{target:'.uk-panel'}" data-uk-grid-margin="">

      <div class="uk-width-medium-1-3 uk-row-first">
        <a class="uk-panel docs-panel-link" href="https://twitter.com/getuikit" style="min-height: 150px;">
          <div class="docs-icon"><i class="uk-icon-twitter uk-icon-large"></i></div>
          <h2>Twitter</h2>
          <p>Follow the developers of UIkit on Twitter<sup class="docs-sup">[2]</sup> and be the first to receive news and updates. They are open for your feedback and questions.</p>
        </a>
      </div>

      <div class="uk-width-medium-1-3">
        <a class="uk-panel docs-panel-link" href="https://www.drupal.org/project/issues/uikit" style="min-height: 150px;">
          <div class="docs-icon"><i class="uk-icon-drupal uk-icon-large"></i></div>
          <h2>Contribute on Drupal</h2>
          <p>You want to take part in the development of UIkit for Drupal<sup class="docs-sup">[1]</sup>? Clone UIkit on Drupal.org and send us a patch. To report a bug, file a new issue.</p>
        </a>
      </div>

      <div class="uk-width-medium-1-3">
        <a class="uk-panel docs-panel-link" href="https://gitter.im/uikit/uikit" style="min-height: 150px;">
          <div class="docs-icon"><i class="uk-icon-comments-o uk-icon-large"></i></div>
          <h2>UIkit Community</h2>
          <p>If you're interested in discussing, participating and helping each other, the UIkit community<sup class="docs-sup">[2]</sup> is the place to be.</p>
        </a>
      </div>

      <div class="uk-width-1-1">
        <ol class="docs-ordered-list docs-section-text-small uk-text-left">
          <li>The UIkit for Drupal project is a fork of the UIkit framework specifically designed to work with Drupal. Although we fully support the work done by YOOtheme and their developers, please restrict issues with UIkit for Drupal to issues directly related to the UIkit for Drupal project. If you happen to file a bug in our issue queue not related to our forked project, we may have to refer you to the official UIkit framework issue queue on GitHub.</li>
          <li>The development of the UIkit framework is headed by YOOtheme, who are not directly associated with the UIkit for Drupal project or this website. We'd still love to thank them for their hard work, we couldn't have done it without them!</li>
        </ol>
      </div>

    </div>

  </div>
</div>
