<div class="uk-panel uk-panel-box uk-panel-header">
  <h3 class="uk-panel-title">UIkit Resources</h3>
  <ul class="uk-list uk-list-line">
    <li><a href="https://www.drupal.org/project/uikit" target="_blank">Drupal.org project page</a></li>
    <li><a href="https://www.drupal.org/project/uikit/releases/7.x-2.2" target="_blank">uikit 7.x-2.2 release page</a></li>
    <li><a href="https://www.drupal.org/project/uikit/releases/7.x-3.0-beta1" target="_blank">uikit 7.x-3.0-beta1 release page</a></li>
    <li><a href="https://www.drupal.org/project/uikit/releases/8.x-2.0-rc3" target="_blank">uikit 8.x-2.0-rc3 release page</a></li>
    <li><a href="https://simplytest.me/project/uikit" target="_blank">Try out a demonstration</a></li>
    <li><a href="https://www.drupal.org/list-changes/uikit" target="_blank">Read complete log of changes</a></li>
    <li><a href="https://www.drupal.org/project/issues/search/uikit?status[0]=8&status[1]=13&status[2]=14" target="_blank">View pending patches</a></li>
    <li><a href="http://drupalcode.org/uikit" target="_blank">Browse code repository</a></li>
    <li><a href="https://www.drupal.org/node/2605968/commits" target="_blank">View commits</a></li>
    <li><a href="https://www.drupal.org/project/usage/uikit" target="_blank">Usage statistics</a></li>
  </ul>
</div>
