<p class="uk-article-lead">Different layout specimens to preview UIkit for Drupal.</p>
<p>This overview gives you a hint of what you can do with UIkit for Drupal. The screenshots below are the same as found <a href="https://getuikit.com/v2/docs/documentation_layouts.html" target="_blank">here</a>, except taken from a clean installation of UIkit and Drupal.</p>

<ul class="uk-subnav uk-subnav-pill" data-uk-switcher="{connect:'#switcher-content'}">
  <li class="uk-active" aria-expanded="true"><a href="#">7.x-2.x</a></li>
  <li aria-expanded="false" class=""><a href="#">7.x-3.x</a></li>
  <li aria-expanded="false" class=""><a href="#">8.x-2.x</a></li>
  <li aria-expanded="false" class=""><a href="#">8.x-3.x</a></li>
</ul>

<ul id="switcher-content" class="uk-switcher">
  <li class="uk-active" aria-hidden="false">
    <div class="uk-grid" data-uk-grid-margin>

      <div class="uk-width-medium-1-3">
        <a href="/profiles/uikit_api/modules/custom/docs_companion/includes/images/7.x-2.x/frontpage.png" data-uk-lightbox="{group:'group1'}" title="Frontpage">
          <img src="/profiles/uikit_api/modules/custom/docs_companion/includes/images/7.x-2.x/frontpage-thumbnail.png" class="uk-thumbnail" alt="Frontpage">
          <div class="uk-thumbnail-caption">Frontpage</div>
        </a>
      </div>

      <div class="uk-width-medium-1-3">
        <a href="/profiles/uikit_api/modules/custom/docs_companion/includes/images/7.x-2.x/portfolio.png" data-uk-lightbox="{group:'group1'}" title="Portfolio">
          <img src="/profiles/uikit_api/modules/custom/docs_companion/includes/images/7.x-2.x/portfolio-thumbnail.png" class="uk-thumbnail" alt="Portfolio">
          <div class="uk-thumbnail-caption">Portfolio</div>
        </a>
      </div>

      <div class="uk-width-medium-1-3">
        <a href="/profiles/uikit_api/modules/custom/docs_companion/includes/images/7.x-2.x/blog.png" data-uk-lightbox="{group:'group1'}" title="Blog">
          <img src="/profiles/uikit_api/modules/custom/docs_companion/includes/images/7.x-2.x/blog-thumbnail.png" class="uk-thumbnail" alt="Blog">
          <div class="uk-thumbnail-caption">Blog</div>
        </a>
      </div>

      <div class="uk-width-medium-1-3">
        <a href="/profiles/uikit_api/modules/custom/docs_companion/includes/images/7.x-2.x/post.png" data-uk-lightbox="{group:'group1'}" title="Post">
          <img src="/profiles/uikit_api/modules/custom/docs_companion/includes/images/7.x-2.x/post-thumbnail.png" class="uk-thumbnail" alt="Post">
          <div class="uk-thumbnail-caption">Post</div>
        </a>
      </div>

      <div class="uk-width-medium-1-3">
        <a href="/profiles/uikit_api/modules/custom/docs_companion/includes/images/7.x-2.x/documentation.png" data-uk-lightbox="{group:'group1'}" title="Documentation">
          <img src="/profiles/uikit_api/modules/custom/docs_companion/includes/images/7.x-2.x/documentation-thumbnail.png" class="uk-thumbnail" alt="Documentation">
          <div class="uk-thumbnail-caption">Documentation</div>
        </a>
      </div>

      <div class="uk-width-medium-1-3">
        <a href="/profiles/uikit_api/modules/custom/docs_companion/includes/images/7.x-2.x/contact.png" data-uk-lightbox="{group:'group1'}" title="Contact">
          <img src="/profiles/uikit_api/modules/custom/docs_companion/includes/images/7.x-2.x/contact-thumbnail.png" class="uk-thumbnail" alt="Contact">
          <div class="uk-thumbnail-caption">Contact</div>
        </a>
      </div>

      <div class="uk-width-medium-1-3">
        <a href="/profiles/uikit_api/modules/custom/docs_companion/includes/images/7.x-2.x/login.png" data-uk-lightbox="{group:'group1'}" title="Login">
          <img src="/profiles/uikit_api/modules/custom/docs_companion/includes/images/7.x-2.x/login.png" class="uk-thumbnail" alt="Login">
          <div class="uk-thumbnail-caption">Login</div>
        </a>
      </div>

    </div>
  </li>

  <li class="uk-active" aria-hidden="false">
    <div class="uk-grid" data-uk-grid-margin>
      <div>
        <p>Coming soon!</p>
      </div>
    </div>
  </li>

  <li class="uk-active" aria-hidden="false">
    <div class="uk-grid" data-uk-grid-margin>
      <div>
        <p>Coming soon!</p>
      </div>
    </div>
  </li>

  <li class="uk-active" aria-hidden="false">
    <div class="uk-grid uk-grid-width-medium-1-2" data-uk-grid-margin>
      <div>
        <p>Coming soon!</p>
      </div>
    </div>
  </li>
</ul>
