<?php

/**
 * @file
 * UIkit Components.
 *
 * Companion module to the UIkit base theme to provide additional components and
 * functionality.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\uikit_components\UIkitComponents;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_help().
 */
function uikit_components_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  $args = [
    '@grid' => 'https://getuikit.com/v2/docs/grid.html',
    '@panel' => 'https://getuikit.com/v2/docs/panel.html',
    '@block' => 'https://getuikit.com/v2/docs/block.html',
    '@cover' => 'https://getuikit.com/v2/docs/cover.html',
    '@nav' => 'https://getuikit.com/v2/docs/nav.html',
    '@subnav' => 'https://getuikit.com/v2/docs/subnav.html',
    '@list' => 'https://getuikit.com/v2/docs/list.html',
    '@table' => 'https://getuikit.com/v2/docs/table.html',
    '@slideshow' => 'https://getuikit.com/v2/docs/slideshow.html',
    '@accordion' => 'https://getuikit.com/v2/docs/accordion.html',
  ];

  switch ($route_name) {
    case 'help.page.uikit_components':
      $output = '<p>' . t('The UIkit components module provides additional components and functionality to the UIkit base theme and various Drupal core modules, such as Views. Some aspects of the frontend cannot be themed without going through the backend, such as empty navbar links and Views display styles. With this module we can add more functionality to the UIkit frontend through the Drupal backend without the need for contributed modules which may add more functionality than needed.') . '</p>';
      $output .= '<h3>' . t('Views style plugins') . '</h3>';
      $output .= '<p>' . t('UIkit Components adds styles to Views to output the results of a view as several common UIkit components. The available views styles are:') . '</p>';
      $output .= '<ul>';
      $output .= '<li>' . t('<a href="@grid" target="_blank">Grid</a>', $args) . '</li>';
      $output .= '<li>' . t('<a href="@list" target="_blank">List</a>', $args) . '</li>';
      $output .= '<li>' . t('<a href="@table" target="_blank">Table</a>', $args) . '</li>';
      $output .= '</ul>';
      $output .= '<p>' . t('<strong>Note</strong>: The 8.x-2.x branch of the UIkit theme is the only supported branch at this time. Once YOOtheme releases a fully-stable version for UIkit 3 we will provide views styles for the UIkit 8.x-3.x branch.') . '</p>';
      break;

    case 'uikit_components.admin':
      $output = '<p>' . t('Admin') . '</p>';
      break;

    case 'uikit_components.core':
      $output = '<p>' . t('UIkit offers over 30 modular and extendible components, which can be combined with each other. Components are divided into different compartments according to their purpose and functionality. This form allows you to control how some of these components are used.') . '</p>';
      break;

    case 'uikit_components.advanced':
      $output = '<p>' . t("UIkit offers some advanced components that are not included in the UIkit core framework. Usually you wouldn't use these components in your everyday website. They include stuff like nestables and datepickers, which will come in handy, if you create advanced user interfaces like administration areas. This form allows you to control how some of these components are used.") . '</p>';
      break;
  }

  return $output;
}

/**
 * Implements hook_theme().
 */
function uikit_components_theme($existing, $type, $theme, $path) {
  return UIkitComponents::getThemeHooks();
}

/**
 * Implements hook_theme_registry_alter().
 */
function uikit_components_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'uikit_components');

  // Alter the path so we can put templates into separate directories.
  $theme_registry['uikit_view_grid']['path'] = $module_path . '/templates/views';
  $theme_registry['uikit_view_list']['path'] = $module_path . '/templates/views';
  $theme_registry['uikit_view_table']['path'] = $module_path . '/templates/views';
}

/**
 * Implements hook_views_preview_info_alter().
 */
function uikit_components_views_preview_info_alter(array &$rows, ViewExecutable $view) {
  $style = $view->getStyle();
  $plugin_id = $style->getPluginId();
  $uikit_plugins = [
    'uikit_view_grid',
    'uikit_view_list',
    'uikit_view_table',
  ];

  if (in_array($plugin_id, $uikit_plugins)) {
    $version = UIkitComponents::getUIkitLibraryVersion();
    $view->element['#attached']['library'][] = "uikit_components/uikit$version";
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function uikit_components_form_menu_link_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $menu_link = $form_state->getFormObject()->getEntity();
  $menu_link_options = $menu_link->link->first()->options ?: [];

  $form['menu_item_type'] = array(
    '#type'          => 'select',
    '#title'         => t('Menu item type'),
    '#default_value' => !empty($menu_link_options['menu_item_type']) ? $menu_link_options['menu_item_type'] : 0,
    '#options' => [
      0 => t('Normal menu item'),
      'nav_header' => t('Navigation header'),
      'nav_divider' => t('Navigation divider'),
    ],
    '#description' => t('Select the type of menu item this is. <em class="placeholder">Navigation header</em> and <em class="placeholder">Navigation divider</em> are special menu items from the <a href="@navbar" target="_blank">UIkit navbar component</a>.', array(
      '@navbar' => 'https://getuikit.com/v2/docs/navbar.html',
    )),
  );

  $form['actions']['submit']['#submit'][] = 'uikit_components_menu_link_content_form_submit';
}

/**
 * Process handler for the menu link content form.
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function uikit_components_menu_link_content_form_submit($form, FormStateInterface $form_state) {
  $menu_item_type = $form_state->getValue('menu_item_type');
  $type = empty($menu_item_type) ? 'normal_menu_item' : $menu_item_type;

  $options = [
    'menu_item_type' => $type,
  ];

  $menu_link = $form_state->getFormObject()->getEntity();
  $menu_link_options = $menu_link->link->first()->options;

  $merged = array_merge($menu_link_options, $options);

  $menu_link->link->first()->options = $merged;
  $menu_link->save();
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function uikit_components_form_block_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $block = $form_state->getFormObject()->getEntity();
  $region = $block->getRegion();

  if ($region == 'navbar') {
    // Add navbar alignment setting to navbar blocks.
    $form['navbar_alignment'] = array(
      '#type' => 'select',
      '#title' => t('Navbar alignment'),
      '#default_value' => $block->getThirdPartySetting('uikit_components', 'navbar_alignment'),
      '#options' => [
        0 => t('Left'),
        1 => t('Right'),
      ],
      '#description' => t('Select the alignment of this menu in the navbar region.'),
      '#weight' => 0,
    );

    // Add a form entity builder.
    $form['#entity_builders'][] = 'uikit_components_form_block_form_builder';
  }
}

/**
 * Entity builder for the block configuration entity.
 */
function uikit_components_form_block_form_builder($entity_type, Drupal\block\Entity\Block $block, &$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  if ($form_state->getValue('navbar_alignment')) {
    $block->setThirdPartySetting('uikit_components', 'navbar_alignment', $form_state->getValue('navbar_alignment'));
    return;
  }

  $block->unsetThirdPartySetting('uikit_components', 'navbar_alignment');
}
